apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  # How the underlying volume would get accessed. [ReadWriteOnce, ReadOnlyMany, ReadWriteMany]
  accessModes:
    - ReadWriteOnce
  # actually volume that needs to be created. (A kind of billboard)
  resources:
    requests:
      storage: 2Gi